const assert = require('node:assert/strict');
const vm = require('node:vm');
const esbuild = require('esbuild');
let now=0, timer=null, removed=0;
const summary={textContent:''};
const chart={style:{},setAttribute(){},getContext:()=>null};
const panel={style:{},append(){},remove(){removed++;}};
const moduleStub={exports:{}};
const source=esbuild.buildSync({entryPoints:['src/renderer/src/frame-debug.ts'],bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;
vm.runInNewContext(source,{module:moduleStub,exports:moduleStub.exports,performance:{now:()=>now},document:{createElement:tag=>tag==='pre'?panel:tag==='span'?summary:chart,body:{appendChild(){}}},setInterval:fn=>{timer=fn;return 1},clearInterval:()=>{timer=null}});
const debug=new moduleStub.exports.FrameDebug();
debug.configure(false,60,false);assert.equal(timer,null);
debug.configure(true,60,false);
for(let i=1;i<=120;i++){now=i*1000/60;debug.draw(now);}
timer();assert.match(summary.textContent,/60.0 fps/);assert.match(summary.textContent,/0회/);
now+=50;debug.draw(now);timer();assert.match(summary.textContent,/1회/);
now+=3000;timer();assert.match(summary.textContent,/1회/);
now+=7100;timer();assert.match(summary.textContent,/0회/);
assert.match(summary.textContent,/최근 10초/);
debug.configure(true,60,true);now+=2100;timer();assert.match(summary.textContent,/일시정지/);assert.match(summary.textContent,/0.0 fps/);
debug.configure(false,60,false);assert.equal(timer,null);assert.equal(removed,1);
console.log('Frame debug: FPS, late frame, idle zero and timer cleanup passed.');
debug.configure(true,60,false);
debug.tick(now,now,true,0,{physics:.2,draw:1,shadow:.6,total:1.3});
now+=16.5;
debug.tick(now,now,false,.16,{physics:.2,draw:0,shadow:0,total:.3});
now+=33.4;
debug.tick(now,now,true,0,{physics:.4,draw:2,shadow:1,total:2.5});
timer();
assert.match(summary.textContent,/Limiter skips 1 \| <=2ms early 1/);
assert.match(summary.textContent,/limiter early 0.16ms/);
assert.match(summary.textContent,/arrival gap 33.4ms/);
assert.match(summary.textContent,/Shadow 1.00 ms/);
now+=10001;timer();assert.match(summary.textContent,/Limiter skips 0/);
debug.configure(false,60,false);assert.equal(timer,null);
console.log('Diagnostics: early skips, callback gaps, stage costs and 10s expiry passed.');
